#!/usr/bin/env bash
# Archive an aur-sleuth report to the audit-reports orphan branch.
# Usage: archive-report.sh <package-name> [report-file]
#   report-file defaults to /tmp/aur-sleuth/aur-sleuth-report-<package-name>.txt
set -euo pipefail

cd "$(dirname "$0")/.."
REPORTS_BRANCH="audit-reports"

pkg="${1:?Usage: archive-report.sh <package-name> [report-file]}"
report_file="${2:-/tmp/aur-sleuth/aur-sleuth-report-${pkg}.txt}"

if [[ ! -f "$report_file" ]]; then
    echo "Error: report file not found: $report_file" >&2
    exit 1
fi

# Extract metadata from YAML frontmatter (preferred) or fall back to body parsing
_fm() { sed -n '/^---$/,/^---$/p' "$report_file" | grep "^${1}:" | head -1 | sed "s/^${1}: *//" ; }

model="$(_fm model)"
result="$(_fm result)"
provider="$(_fm provider)"

# Fall back to body parsing for reports without frontmatter
if [[ -z "$model" ]]; then
    model="$(grep -oP '^\s*Models?:\s*\K\S+' "$report_file" | head -1 || echo "unknown")"
fi
if [[ -z "$result" ]]; then
    result="$(grep -oP 'Final Status:\s*\K\S+' "$report_file" | head -1 || echo "unknown")"
    result="$(echo "$result" | tr '[:upper:]' '[:lower:]')"
fi
if [[ -z "$provider" ]]; then
    base_url="$(grep -oP 'with \S+ from \K\S+' "$report_file" | head -1 || echo "unknown")"
    if [[ "$base_url" != "unknown" ]]; then
        provider="$(echo "$base_url" | sed -E 's|https?://([^/]+).*|\1|')"
    else
        provider="unknown"
    fi
fi

filename="$(date -u +%Y%m%d-%H%M%S)-${model//\//-}.md"

# The report file already contains YAML frontmatter if generated by a
# recent aur-sleuth version. Use it as-is (renaming to .md for the branch).
md_content="$(cat "$report_file")"

# Git plumbing: add to audit-reports branch without checking it out
tmpindex="$(mktemp)"
rm -f "$tmpindex"

if git rev-parse --verify "$REPORTS_BRANCH" &>/dev/null; then
    GIT_INDEX_FILE="$tmpindex" git read-tree "$REPORTS_BRANCH"
fi

blob_hash="$(echo "$md_content" | git hash-object -w --stdin)"
GIT_INDEX_FILE="$tmpindex" git update-index --add \
    --cacheinfo "100644,${blob_hash},${pkg}/${filename}"
tree_hash="$(GIT_INDEX_FILE="$tmpindex" git write-tree)"

parent_args=()
if git rev-parse --verify "$REPORTS_BRANCH" &>/dev/null; then
    parent_args=(-p "$REPORTS_BRANCH")
fi

commit_hash="$(git commit-tree "$tree_hash" \
    "${parent_args[@]}" \
    -m "audit: ${pkg} (${result}) [${model}]")"

git update-ref "refs/heads/${REPORTS_BRANCH}" "$commit_hash"
rm -f "$tmpindex"

echo "Stored: ${REPORTS_BRANCH}:${pkg}/${filename}"
