#!/usr/bin/env bash
# Archive an aur-sleuth report to the audit-reports orphan branch.
# Usage: archive-report.sh <package-name> [report-file]
#   report-file defaults to /tmp/aur-sleuth/aur-sleuth-report-<package-name>.txt
set -euo pipefail

cd "$(dirname "$0")/.."
REPORTS_BRANCH="audit-reports"

pkg="${1:?Usage: archive-report.sh <package-name> [report-file]}"
report_file="${2:-/tmp/aur-sleuth/aur-sleuth-report-${pkg}.txt}"

if [[ ! -f "$report_file" ]]; then
    echo "Error: report file not found: $report_file" >&2
    exit 1
fi

# Metadata comes from the YAML frontmatter, and only from there. Every report
# aur-sleuth finishes has one; a file without one is a stub from a run that
# crashed before any model answered, holding nothing but the tool's own lines.
# Archiving that would call the package "audited" (its version enters the
# audited index and suppresses the retry) under a model and verdict of
# "unknown". aur-sleuth removes such a stub itself; refusing here is the
# check that it did.
_fm() { sed -n '/^---$/,/^---$/p' "$report_file" | grep "^${1}:" | head -1 | sed "s/^${1}: *//" || true; }

model="$(_fm model)"
result="$(_fm result)"

if [[ -z "$model" || -z "$result" ]]; then
    echo "Error: $report_file has no frontmatter; a report no model answered is not archived" >&2
    exit 2
fi

filename="$(date -u +%Y%m%d-%H%M%S)-${model//\//-}.md"

# The branch never forgets: every clone carries every blob ever archived, so
# one pathological report -- a model pasting file contents into its answer --
# would cost every future clone forever. The largest legitimate report to
# date is 260 KB; 2 MB is generous headroom. Truncating rather than refusing
# keeps the frontmatter (it leads the file), so the package still counts as
# audited and is not silently re-audited at full cost on every later run.
max_bytes="${AUR_SLEUTH_MAX_REPORT_BYTES:-2097152}"
size="$(wc -c < "$report_file")"
if (( size > max_bytes )); then
    echo "Warning: report is ${size} bytes (cap ${max_bytes}); archiving a truncated copy" >&2
    md_content="$(head -c "$max_bytes" "$report_file")

[TRUNCATED: the report was ${size} bytes; the archive keeps the first ${max_bytes}]"
else
    # The report file already contains YAML frontmatter if generated by a
    # recent aur-sleuth version. Use it as-is (renaming to .md for the branch).
    md_content="$(cat "$report_file")"
fi

# Resolve what this commit builds on. When only the remote copy of the branch exists --
# a fresh clone, or any checkout that never fetched it into a local ref -- seed from
# origin. Skipping this step does not fail loudly: the plumbing below would build a
# PARENTLESS commit over an empty index, then repoint the branch at a tree holding only
# this one report, silently discarding every report already archived.
base_ref=""
if git rev-parse --verify --quiet "refs/heads/${REPORTS_BRANCH}" >/dev/null; then
    base_ref="refs/heads/${REPORTS_BRANCH}"
elif git rev-parse --verify --quiet "refs/remotes/origin/${REPORTS_BRANCH}" >/dev/null; then
    base_ref="refs/remotes/origin/${REPORTS_BRANCH}"
    echo "Note: local ${REPORTS_BRANCH} is absent; basing this commit on origin/${REPORTS_BRANCH}"
fi

# Git plumbing: add to audit-reports branch without checking it out
tmpindex="$(mktemp)"
rm -f "$tmpindex"

if [[ -n "$base_ref" ]]; then
    GIT_INDEX_FILE="$tmpindex" git read-tree "$base_ref"
fi

blob_hash="$(echo "$md_content" | git hash-object -w --stdin)"
GIT_INDEX_FILE="$tmpindex" git update-index --add \
    --cacheinfo "100644,${blob_hash},${pkg}/${filename}"
tree_hash="$(GIT_INDEX_FILE="$tmpindex" git write-tree)"

parent_args=()
if [[ -n "$base_ref" ]]; then
    parent_args=(-p "$base_ref")
fi

commit_hash="$(git commit-tree "$tree_hash" \
    "${parent_args[@]}" \
    -m "audit: ${pkg} (${result}) [${model}]")"

git update-ref "refs/heads/${REPORTS_BRANCH}" "$commit_hash"
rm -f "$tmpindex"

echo "Stored: ${REPORTS_BRANCH}:${pkg}/${filename}"
