#!/usr/bin/env bash
# Archive an aur-sleuth report to the audit-reports orphan branch.
# Usage: archive-report.sh <package-name> [report-file]
#   report-file defaults to /tmp/aur-sleuth/aur-sleuth-report-<package-name>.txt
set -euo pipefail

cd "$(dirname "$0")/.."
REPORTS_BRANCH="audit-reports"

pkg="${1:?Usage: archive-report.sh <package-name> [report-file]}"
report_file="${2:-/tmp/aur-sleuth/aur-sleuth-report-${pkg}.txt}"

if [[ ! -f "$report_file" ]]; then
    echo "Error: report file not found: $report_file" >&2
    exit 1
fi

# Extract metadata from YAML frontmatter (preferred) or fall back to body parsing
_fm() { sed -n '/^---$/,/^---$/p' "$report_file" | grep "^${1}:" | head -1 | sed "s/^${1}: *//" ; }

model="$(_fm model)"
result="$(_fm result)"

# Fall back to body parsing for reports without frontmatter
if [[ -z "$model" ]]; then
    model="$(grep -oP '^\s*Models?:\s*\K\S+' "$report_file" | head -1 || echo "unknown")"
fi
if [[ -z "$result" ]]; then
    result="$(grep -oP 'Final Status:\s*\K\S+' "$report_file" | head -1 || echo "unknown")"
    result="$(echo "$result" | tr '[:upper:]' '[:lower:]')"
fi

filename="$(date -u +%Y%m%d-%H%M%S)-${model//\//-}.md"

# The report file already contains YAML frontmatter if generated by a
# recent aur-sleuth version. Use it as-is (renaming to .md for the branch).
md_content="$(cat "$report_file")"

# Resolve what this commit builds on. When only the remote copy of the branch exists --
# a fresh clone, or any checkout that never fetched it into a local ref -- seed from
# origin. Skipping this step does not fail loudly: the plumbing below would build a
# PARENTLESS commit over an empty index, then repoint the branch at a tree holding only
# this one report, silently discarding every report already archived.
base_ref=""
if git rev-parse --verify --quiet "refs/heads/${REPORTS_BRANCH}" >/dev/null; then
    base_ref="refs/heads/${REPORTS_BRANCH}"
elif git rev-parse --verify --quiet "refs/remotes/origin/${REPORTS_BRANCH}" >/dev/null; then
    base_ref="refs/remotes/origin/${REPORTS_BRANCH}"
    echo "Note: local ${REPORTS_BRANCH} is absent; basing this commit on origin/${REPORTS_BRANCH}"
fi

# Git plumbing: add to audit-reports branch without checking it out
tmpindex="$(mktemp)"
rm -f "$tmpindex"

if [[ -n "$base_ref" ]]; then
    GIT_INDEX_FILE="$tmpindex" git read-tree "$base_ref"
fi

blob_hash="$(echo "$md_content" | git hash-object -w --stdin)"
GIT_INDEX_FILE="$tmpindex" git update-index --add \
    --cacheinfo "100644,${blob_hash},${pkg}/${filename}"
tree_hash="$(GIT_INDEX_FILE="$tmpindex" git write-tree)"

parent_args=()
if [[ -n "$base_ref" ]]; then
    parent_args=(-p "$base_ref")
fi

commit_hash="$(git commit-tree "$tree_hash" \
    "${parent_args[@]}" \
    -m "audit: ${pkg} (${result}) [${model}]")"

git update-ref "refs/heads/${REPORTS_BRANCH}" "$commit_hash"
rm -f "$tmpindex"

echo "Stored: ${REPORTS_BRANCH}:${pkg}/${filename}"
